### PR TITLE
Update IPP.php

### PR DESCRIPTION
**Pull request by Traqza**
quickbooks/v3-php-sdk/src\Data\IPP.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

### CODE REVIEW

**Comment by abisalehalliprasan** [comment]
Thanks @Traqza  . 

Will review your PR soon. Thanks for the contribution 🚀

**Comment by matthewhutchings** [comment]
Please can this be merged. Composer 2 has been upgraded and this is causing issues.

**Comment by hotmeteor** [comment]
Any updates?

**Comment by danabrey** [comment]
Should this be updated on this line too?
https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/361/files#diff-8d5f950d77a75e300294395ad65937126d90695bd8dc3285855c26326023ab5bR26

**Comment by danabrey** [comment]
Sorry, I meant this line:

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/aa377f9b5e54dc54eba652fc30255335a790ea57/src/Data/IPP.php#L26

**Comment by abisalehalliprasan** [comment]
This should be fixed with the release: [6.0.0](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/6.0.0)

**Pull request closed without merging**
