### PR TITLE
code style and PHPDoc fixes

### PR DESCRIPTION
**Pull request by becquerel**
This commit does not change behavior, it just unifies formatting across the file, fixes some minor bugs, typos and PHPDoc, so it can be better used as a reference

If this is approved, I will appreciate it (it is easier to work with `DataService` if all code completion actually works correctly), if not, no big deal

### CODE REVIEW

**Comment by hlu2** [comment]
Hi becquerel,

   Thanks your commit! It is a lot of work to fix the documentation. It will make the SDK documentation much clearer!
    Just let you know, I am currently working on the dataService class to remove the PECL OAuth 1.0 extension requirements. Please don't make more changes to the dataService class as I will not able to accept pull request anymore in the future.
   
Best,
Hao

**Comment by becquerel** [comment]
@hlu2 thank you. I won't make any more changes then. Does this mean no more community-provided pull requests will be accepted ? Or is it a temporary state until you resolve this issue ?

**Comment by hlu2** [comment]
@becquerel It is a temporary state. You can still make changes to the classes located outside of the /core/HttpClients/ folder. The release should go out soon.

**Comment by becquerel** [comment]
Perfect, thank you !

**Pull request merged**
