### PR TITLE
Fixes for SyncRestHandler/ServiceContext/Use Imports/Code Style

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This PR is quite big and contains a lot of changes and fixes:

1. Check if Type of ServiceContext is instanceof ServiceContext (was done using strcmp and get_class, which was not working)
2. Fix Imports of CoreConstants Class in some cases
3. Fix PHP-DocType for SimpleXMLElement
4. Run CS-Fixer to fix the Coding Style
5. Fixed an issue with PlatformServices -> did use the QB Url instead of IPP
6. Fixed an Inheritance Problem in SyncRestHandler.

If you merge it, I am happy, if not, still not end of the world, I can use my fork instead.

Regards
Dominik

### CODE REVIEW

**Comment by hlu2** [comment]
Thanks for contribution.

**Comment by challgren** [comment]
What standard/options did you use for the php-cs?

**Comment by dpfaffenbauer** [comment]
@challgren excellent question.... I actually don't know anymore. Usually I use PSR Standards.

**Comment by challgren** [comment]
Damm ok. Yeah I used PSR2 but it didn't match your commits.

**Pull request merged**
