### PR TITLE
the Quickbooks API expects the class paramater to be named  'class' in…

### PR DESCRIPTION
**Pull request by lukereimer**
…stead of 'classid'

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@hlu2 This is a blocking bug for us.  Is there anyway that you can address this issue.  We are trying to pull P&L's by class & until this is addressed we cannot use the SDK without "hacking" the vendor code.

Please let us know if there is anything that we can do to help!

Thanks so much for all that you do.

**Comment by jimmypuckett** [comment]
@hlu2, is there anything different that you would like to see done on this PR so that we could get it merged in?  This bug is the way that the SDK does not work with classes is really holding us up & I would be happy to help out in whatever way that we could to see this fix make it into the official release so that we done have to use a forked version.

Thanks for your time!

**Comment by hlu2** [comment]
@lukereimer 
Thanks for your contribution, I was working on other project. I have approved your merge request.

**Comment by hlu2** [comment]
I will make a new release by the end of this week.

**Comment by lukereimer** [comment]
@hlu2 thanks!

**Pull request merged**
