### PR TITLE
Phpstan

### PR DESCRIPTION
**Pull request by challgren**
This is the start of the PHPStan fixes. This also includes fixes provided by #168

### CODE REVIEW

**Comment by challgren** [comment]
Also fixes #172

**Comment by challgren** [comment]
Need to fix Travis PHP 5.6 to not include PHPStan since it requires PHP 7

**Comment by challgren** [comment]
@hlu2 This is completed. Basically what I did was go through and clean up the docs so they match what type they return. You can now run composer phpstan and it will check the code for common typos and easily overlooked code. Also fixes #168 and #146 and makes it an alias and a deprecated warning. Also updated the XSD conversion script drastically to 1 not produce bad code that PHPStan complains about. And updates the XSD minor version to 26 thus allowing the API to go all the way up to minor version 30 now. Also you'll need to update travis ci to not include PHPStan since it only works with PHP 7 but can process PHP 5.6 codebases

**Comment by challgren** [comment]
Travis CI has been fixed. I did remove the tests for PHP 5.6 since in 3 months security support will end and it will no longer be support. https://secure.php.net/supported-versions.php 

You may also want to squash the commits when you merge.

**Comment by hlu2** [comment]
Hi Chris,

I will review this on weekend and merge it. Thanks again for your contribution!

Best,
Hao

**Comment by challgren** [comment]
@hlu2 I know your busy but any luck reviewing this yet?

**Comment by hlu2** [comment]
@challgren 
Just get it tested and it worked great! Thanks for your contribution!

**Pull request merged**
